version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5079:5079"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - .env.local
